import type { Database } from './database.types';

type Language = Database['public']['Tables']['languages']['Row'];
type Lesson = Database['public']['Tables']['lessons']['Row'];
type Vocabulary = Database['public']['Tables']['vocabulary']['Row'];
type QuizQuestion = Database['public']['Tables']['quiz_questions']['Row'];

export const mockLanguages: Language[] = [
  {
    id: 'kikuyu-1',
    name: 'Kikuyu',
    tribe_name: 'Kikuyu',
    description: 'The language of the Kikuyu people, the largest ethnic group in Kenya. Spoken primarily in Central Kenya.',
    total_speakers: 8000000,
    counties: ['Kiambu', 'Murang\'a', 'Nyeri', 'Kirinyaga', 'Nyandarua'],
    flag_emoji: '🏔️',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'luo-1',
    name: 'Dholuo',
    tribe_name: 'Luo',
    description: 'The language of the Luo people, primarily spoken around Lake Victoria. Rich in oral traditions and poetry.',
    total_speakers: 5000000,
    counties: ['Kisumu', 'Siaya', 'Homa Bay', 'Migori', 'Kisii'],
    flag_emoji: '🐟',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'luhya-1',
    name: 'Luhya',
    tribe_name: 'Luhya',
    description: 'A collective of dialects spoken by the Luhya people in Western Kenya. Known for its rich cultural heritage.',
    total_speakers: 6000000,
    counties: ['Kakamega', 'Bungoma', 'Vihiga', 'Busia'],
    flag_emoji: '🌾',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'kamba-1',
    name: 'Kikamba',
    tribe_name: 'Kamba',
    description: 'The language of the Kamba people from Eastern Kenya. Known for their artistic traditions and craftsmanship.',
    total_speakers: 4500000,
    counties: ['Machakos', 'Kitui', 'Makueni'],
    flag_emoji: '🎨',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-1',
    name: 'Kalenjin',
    tribe_name: 'Kalenjin',
    description: 'A Southern Nilotic language spoken by the Kalenjin people of the Rift Valley. Known for its tonal nature and the community\'s rich athletic heritage and pastoral traditions.',
    total_speakers: 5500000,
    counties: ['Nandi', 'Uasin Gishu', 'Elgeyo-Marakwet', 'Baringo', 'Kericho', 'Bomet', 'Nakuru', 'Trans-Nzoia'],
    flag_emoji: '🏃',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const mockLessons: Lesson[] = [
  {
    id: 'lesson-1',
    language_id: 'kikuyu-1',
    title: 'Basic Greetings',
    description: 'Learn how to greet people in Kikuyu language',
    order_index: 1,
    xp_reward: 50,
    difficulty_level: 'Beginner',
    lesson_type: 'vocabulary',
    created_at: new Date().toISOString(),
  },
  {
    id: 'lesson-2',
    language_id: 'kikuyu-1',
    title: 'Family Members',
    description: 'Learn words for family members and relatives',
    order_index: 2,
    xp_reward: 75,
    difficulty_level: 'Beginner',
    lesson_type: 'vocabulary',
    created_at: new Date().toISOString(),
  },
  {
    id: 'lesson-3',
    language_id: 'luo-1',
    title: 'Basic Greetings',
    description: 'Learn how to greet people in Dholuo',
    order_index: 1,
    xp_reward: 50,
    difficulty_level: 'Beginner',
    lesson_type: 'vocabulary',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-lesson-1',
    language_id: 'kalenjin-1',
    title: 'Basic Greetings & Introductions',
    description: 'Learn essential greetings and how to introduce yourself in Kalenjin',
    order_index: 1,
    xp_reward: 50,
    difficulty_level: 'Beginner',
    lesson_type: 'vocabulary',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-lesson-2',
    language_id: 'kalenjin-1',
    title: 'Family & Relationships',
    description: 'Learn the Kalenjin words for family members and understand family structure',
    order_index: 2,
    xp_reward: 75,
    difficulty_level: 'Beginner',
    lesson_type: 'vocabulary',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-lesson-3',
    language_id: 'kalenjin-1',
    title: 'Numbers & Counting',
    description: 'Master counting from 1 to 10 and learn basic number usage in daily life',
    order_index: 3,
    xp_reward: 75,
    difficulty_level: 'Beginner',
    lesson_type: 'vocabulary',
    created_at: new Date().toISOString(),
  },
];

export const mockVocabulary: Vocabulary[] = [
  {
    id: 'vocab-1',
    lesson_id: 'lesson-1',
    word_or_phrase: 'Wega',
    translation: 'Hello',
    pronunciation: 'weh-gah',
    example_sentence: 'Wega, wee uri ata? - Hello, how are you?',
    audio_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vocab-2',
    lesson_id: 'lesson-1',
    word_or_phrase: 'Ndi njega',
    translation: 'I am fine',
    pronunciation: 'n-dee n-jeh-gah',
    example_sentence: 'Ndi njega, nengiu - I am fine, thank you',
    audio_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vocab-3',
    lesson_id: 'lesson-1',
    word_or_phrase: 'Nengiu',
    translation: 'Thank you',
    pronunciation: 'neh-ngu',
    example_sentence: 'Nengiu muno - Thank you very much',
    audio_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vocab-4',
    lesson_id: 'lesson-1',
    word_or_phrase: 'Uirituanire',
    translation: 'Good morning',
    pronunciation: 'oo-ee-ree-too-ah-nee-reh',
    example_sentence: 'Uirituanire, ndi njega - Good morning, I am fine',
    audio_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-vocab-1-1',
    lesson_id: 'kalenjin-lesson-1',
    word_or_phrase: 'Chamge',
    translation: 'Hello/Greetings',
    pronunciation: 'cham-geh',
    example_sentence: 'Chamge! Inutye nee? - Hello! How are you?',
    audio_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-vocab-1-2',
    lesson_id: 'kalenjin-lesson-1',
    word_or_phrase: 'Inutye nee?',
    translation: 'How are you?',
    pronunciation: 'ee-noo-tyeh neh',
    example_sentence: 'Inutye nee? Achen - How are you? I am fine',
    audio_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-vocab-1-3',
    lesson_id: 'kalenjin-lesson-1',
    word_or_phrase: 'Achen',
    translation: 'I am fine',
    pronunciation: 'ah-chen',
    example_sentence: 'Achen, kong\'ai - I am fine, thank you',
    audio_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-vocab-1-4',
    lesson_id: 'kalenjin-lesson-1',
    word_or_phrase: 'Kong\'ai',
    translation: 'Thank you',
    pronunciation: 'kong-eye',
    example_sentence: 'Kong\'ai missing - Thank you very much',
    audio_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-vocab-1-5',
    lesson_id: 'kalenjin-lesson-1',
    word_or_phrase: 'Sere',
    translation: 'Good morning',
    pronunciation: 'seh-reh',
    example_sentence: 'Sere! Inutye nee? - Good morning! How are you?',
    audio_url: '',
    created_at: new Date().toISOString(),
  },
];

export const mockQuizQuestions: QuizQuestion[] = [
  {
    id: 'quiz-1',
    lesson_id: 'lesson-1',
    question_text: 'What is the Kikuyu word for "Hello"?',
    correct_answer: 'Wega',
    option_a: 'Wega',
    option_b: 'Nengiu',
    option_c: 'Njega',
    option_d: 'Uiri',
    explanation: 'Wega is the most common greeting in Kikuyu, similar to "hello" in English.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'quiz-2',
    lesson_id: 'lesson-1',
    question_text: 'How do you say "Thank you" in Kikuyu?',
    correct_answer: 'Nengiu',
    option_a: 'Wega',
    option_b: 'Nengiu',
    option_c: 'Njega',
    option_d: 'Uiri',
    explanation: 'Nengiu means "thank you" in Kikuyu and is used to express gratitude.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'quiz-3',
    lesson_id: 'lesson-1',
    question_text: 'What does "Ndi njega" mean?',
    correct_answer: 'I am fine',
    option_a: 'Hello',
    option_b: 'I am fine',
    option_c: 'Thank you',
    option_d: 'Good morning',
    explanation: '"Ndi njega" is the response to "how are you?" and means "I am fine".',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-quiz-1-1',
    lesson_id: 'kalenjin-lesson-1',
    question_text: 'What is the Kalenjin word for "Hello"?',
    correct_answer: 'Chamge',
    option_a: 'Chamge',
    option_b: 'Kong\'ai',
    option_c: 'Achen',
    option_d: 'Sere',
    explanation: 'Chamge is the standard greeting in Kalenjin, used throughout the day to greet people.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-quiz-1-2',
    lesson_id: 'kalenjin-lesson-1',
    question_text: 'How do you say "Thank you" in Kalenjin?',
    correct_answer: 'Kong\'ai',
    option_a: 'Chamge',
    option_b: 'Kong\'ai',
    option_c: 'Achen',
    option_d: 'Sere',
    explanation: 'Kong\'ai means "thank you" in Kalenjin and is essential for polite conversation.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kalenjin-quiz-1-3',
    lesson_id: 'kalenjin-lesson-1',
    question_text: 'What does "Achen" mean?',
    correct_answer: 'I am fine',
    option_a: 'Hello',
    option_b: 'Thank you',
    option_c: 'Good morning',
    option_d: 'I am fine',
    explanation: 'Achen is the response meaning "I am fine" when someone asks how you are.',
    created_at: new Date().toISOString(),
  },
];
